name: Delopy
on:
  - push
jobs:
  install-environment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: npm install
        run: |
          npm install
