# node
name: Deploy

env:
  SERVICE_NAME: 'smart-analytics'
  S3_EXTRA_PATH: ''

on:
  push:
    branches:
      - dev
      - release-*
    tags:
      - '*'

concurrency:
  group: '${{ github.workflow }}:${{ github.ref }}@${{ github.repository }}'
  cancel-in-progress: true

jobs:
  environment:
    runs-on: ubuntu-latest
    outputs:
      envs: '${{ toJSON(steps.run.outputs) }}'
    steps:
      - name: Checkout environment action
        uses: actions/checkout@v3
        with:
          repository: starlight-bd/sn-git-actions
          ref: environment@v2
          token: ${{ secrets.ORG_DEVOPS_READ_REPO_WRITE_PACKAGE }}
          path: .github/actions/environment

      - name: Run environment action
        id: run
        uses: ./.github/actions/environment
        with:
          service-name: '${{ env.SERVICE_NAME }}'

  dev:
    runs-on: ubuntu-latest
    needs: [environment]
    environment: dev
    outputs:
      image: ${{ steps.deploy.outputs.image }}
    steps:
      - uses: actions/checkout@v3

      - name: Checkout node action
        uses: actions/checkout@v3
        with:
          repository: starlight-bd/sn-git-actions
          ref: node
          token: ${{ secrets.ORG_DEVOPS_READ_REPO_WRITE_PACKAGE }}
          path: .github/actions/node

      - name: Run node action
        uses: ./.github/actions/node
        id: deploy
        with:
          secrets: '${{ toJSON(secrets) }}'
          envs: '${{ needs.environment.outputs.envs }}'
          extra-path: '${{ env.S3_EXTRA_PATH }}'

  prod:
    runs-on: ubuntu-latest
    needs: [environment, dev]
    environment: prod
    if: fromJSON(needs.environment.outputs.envs).IS_PROD == 'true'
    steps:
      - uses: actions/checkout@v3

      - name: Checkout prod-image action
        uses: actions/checkout@v3
        with:
          repository: starlight-bd/sn-git-actions
          ref: prod-image
          token: ${{ secrets.ORG_DEVOPS_READ_REPO_WRITE_PACKAGE }}
          path: .github/actions/prod-image

      - name: Run prod-image action
        uses: ./.github/actions/prod-image
        with:
          secrets: '${{ toJSON(secrets) }}'
          image: '${{ needs.dev.outputs.image }}'
