name: Delopy
on:
  - push
env:
  DAY_OF_WEEK: Monday
  node_version: ''
jobs:
  install-environment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version || '16' }}"
      - name: npm install
        run: npm install
