name: Delopy
on:
  - push
jobs:
  install-environment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 16.3.0
          registry-url: https://npm.pkg.github.com/
          cache: npm
          always-auth: true
          email: tianna.chen@supernovatech.com
      - name: npm install
        run: npm install --no-audit
        shell: bash
        env:
          NODE_AUTH_TOKEN: dGlhbm5hLmNoZW46VmxaRkh1bTNsSTBz
