name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: run echo
        run: |
          echo '${{toJSON(secrets)}}'
