name: Delopy
on:
  - push
jobs:
  install-environment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 16.3.0
          registry-url: https://nexus.snc-tools.com:1443/repository/dev-sn-npm-repository-group/
          _auth: dGlhbm5hLmNoZW46VmxaRkh1bTNsSTBz
          email: tianna.chen@supernovatech.com
          cache: npm
      - name: npm install
        run: |
          npm ci
