name: Delopy
on:
  - push
jobs:
  install-environment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 16.3.0
          cache: npm
      - name: npm install
        run: echo ${{toJSON(steps)}}
